---
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: develop
    channel: beta
    prerelease: true
tagFormat:
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"